version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bmp_postgres
    restart: always
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - bmp_data:/var/lib/postgresql/data
    networks:
      - bmp_net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U BMP_user -d BMP_DB -h db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    container_name: app
    restart: always
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bmp_net

  airflow_service:
    build: ./airflow_service
    container_name: airflow_service
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
    networks:
      - bmp_net

networks:
  bmp_net:

volumes:
  bmp_data: