"""third migration

Revision ID: 49a2e84fd3e3
Revises: d517d08f3527
Create Date: 2024-10-11 23:48:48.453616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49a2e84fd3e3'
down_revision: Union[str, None] = 'd517d08f3527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'prev_close_price_cur',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'prev_close_price_rub',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'nominal_cur',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'nominal_rub',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'coupon_rate',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'accum_coupon_cur',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'accum_coupon_rub',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.DECIMAL(precision=20, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'accum_coupon_rub',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'accum_coupon_cur',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'coupon_rate',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'nominal_rub',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'nominal_cur',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'prev_close_price_rub',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    op.alter_column('bonds', 'prev_close_price_cur',
               existing_type=sa.DECIMAL(precision=20, scale=4),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###
