"""seventh migration

Revision ID: 8bd3b4ab51a1
Revises: 29ccf170a795
Create Date: 2024-10-21 12:50:29.269546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd3b4ab51a1'
down_revision: Union[str, None] = '29ccf170a795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('prevwaprice_cur', sa.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('bonds', sa.Column('prevwaprice_rub', sa.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('bonds', sa.Column('coupon_value_cur', sa.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('bonds', sa.Column('coupon_value_rub', sa.DECIMAL(precision=20, scale=4), nullable=True))
    op.add_column('bonds', sa.Column('cur_of_nominal', sa.String(), nullable=True))
    op.add_column('bonds', sa.Column('cur_of_market', sa.String(), nullable=True))
    op.drop_column('bonds', 'coupon_rate')
    op.drop_column('bonds', 'valuta_nominal')
    op.drop_column('bonds', 'currency_curr')
    op.drop_column('bonds', 'prev_close_price_rub')
    op.drop_column('bonds', 'prev_close_price_cur')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bonds', sa.Column('prev_close_price_cur', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('prev_close_price_rub', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('currency_curr', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('valuta_nominal', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bonds', sa.Column('coupon_rate', sa.NUMERIC(precision=20, scale=4), autoincrement=False, nullable=True))
    op.drop_column('bonds', 'cur_of_market')
    op.drop_column('bonds', 'cur_of_nominal')
    op.drop_column('bonds', 'coupon_value_rub')
    op.drop_column('bonds', 'coupon_value_cur')
    op.drop_column('bonds', 'prevwaprice_rub')
    op.drop_column('bonds', 'prevwaprice_cur')
    # ### end Alembic commands ###
