"""initial migration

Revision ID: a75e306c2ed4
Revises: 
Create Date: 2024-10-11 14:56:51.580272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75e306c2ed4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prev_close_price_cur', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('prev_close_price_rub', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('nominal_cur', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('nominal_rub', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('coupon_rate', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('coupon_period', sa.Integer(), nullable=False),
    sa.Column('accum_coupon_cur', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('accum_coupon_rub', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('valuta_nominal', sa.String(), nullable=False),
    sa.Column('currency_curr', sa.String(), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('issue_size', sa.Integer(), nullable=False),
    sa.Column('prev_date', sa.DateTime(), nullable=False),
    sa.Column('next_coupon_date', sa.DateTime(), nullable=False),
    sa.Column('maturity_date', sa.DateTime(), nullable=False),
    sa.Column('loading_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ticker')
    )
    op.create_index(op.f('ix_bonds_id'), 'bonds', ['id'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(), nullable=False),
    sa.Column('currency_code', sa.String(), nullable=False),
    sa.Column('curs', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_bonds_id'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
