"""secondary migration

Revision ID: d517d08f3527
Revises: a75e306c2ed4
Create Date: 2024-10-11 23:28:26.166071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd517d08f3527'
down_revision: Union[str, None] = 'a75e306c2ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bonds_name_key', 'bonds', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bonds_name_key', 'bonds', ['name'])
    # ### end Alembic commands ###
