"""fourth migration

Revision ID: f6aa4cee3ad6
Revises: 49a2e84fd3e3
Create Date: 2024-10-12 00:11:14.483524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6aa4cee3ad6'
down_revision: Union[str, None] = '49a2e84fd3e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'prev_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bonds', 'next_coupon_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bonds', 'maturity_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bonds', 'maturity_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bonds', 'next_coupon_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('bonds', 'prev_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
